name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    checks: write

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.9.1
    - name: Run Clippy
      uses: auguwu/clippy-action@1.5.0
      with:
        check-args: --workspace --all-features --all-targets
        args: -D warnings
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Run tests
      run: cargo test --workspace --verbose --all-features
